#include "gl_loader.hpp"

#define GL_FUNC_IMPL(name) PFNGL##name##PROC gl##name = nullptr;
GL_FUNC_IMPL(GENVERTEXARRAYS)
GL_FUNC_IMPL(BINDVERTEXARRAY)
GL_FUNC_IMPL(DELETEVERTEXARRAYS)
GL_FUNC_IMPL(GENBUFFERS)
GL_FUNC_IMPL(BINDBUFFER)
GL_FUNC_IMPL(DELETEBUFFERS)
GL_FUNC_IMPL(BUFFERDATA)
GL_FUNC_IMPL(BUFFERSUBDATA)
GL_FUNC_IMPL(VERTEXATTRIBPOINTER)
GL_FUNC_IMPL(ENABLEVERTEXATTRIBARRAY)
GL_FUNC_IMPL(CREATESHADER)
GL_FUNC_IMPL(SHADERSOURCE)
GL_FUNC_IMPL(COMPILESHADER)
GL_FUNC_IMPL(GETSHADERIV)
GL_FUNC_IMPL(GETSHADERINFOLOG)
GL_FUNC_IMPL(CREATEPROGRAM)
GL_FUNC_IMPL(ATTACHSHADER)
GL_FUNC_IMPL(LINKPROGRAM)
GL_FUNC_IMPL(GETPROGRAMIV)
GL_FUNC_IMPL(GETPROGRAMINFOLOG)
GL_FUNC_IMPL(USEPROGRAM)
GL_FUNC_IMPL(GENFRAMEBUFFERS)
GL_FUNC_IMPL(BINDFRAMEBUFFER)
GL_FUNC_IMPL(FRAMEBUFFERTEXTURE2D)
GL_FUNC_IMPL(CHECKFRAMEBUFFERSTATUS)
GL_FUNC_IMPL(BLITFRAMEBUFFER)
GL_FUNC_IMPL(GETUNIFORMLOCATION)
GL_FUNC_IMPL(UNIFORM1F)
GL_FUNC_IMPL(UNIFORM1I)
GL_FUNC_IMPL(UNIFORM2F)
GL_FUNC_IMPL(UNIFORM3F)
GL_FUNC_IMPL(UNIFORM4F)
GL_FUNC_IMPL(UNIFORMMATRIX4FV)
GL_FUNC_IMPL(DELETEPROGRAM)
GL_FUNC_IMPL(MAPBUFFER)
GL_FUNC_IMPL(UNMAPBUFFER)
GL_FUNC_IMPL(ACTIVETEXTURE)

void loadGLFunctions() {
    auto load = [](const char* name) { return (void*)wglGetProcAddress(name); };
    glGENVERTEXARRAYS = (PFNGLGENVERTEXARRAYSPROC)load("glGenVertexArrays");
    glBINDVERTEXARRAY = (PFNGLBINDVERTEXARRAYPROC)load("glBindVertexArray");
    glGENBUFFERS = (PFNGLGENBUFFERSPROC)load("glGenBuffers");
    glBINDBUFFER = (PFNGLBINDBUFFERPROC)load("glBindBuffer");
    glBUFFERDATA = (PFNGLBUFFERDATAPROC)load("glBufferData");
    glBUFFERSUBDATA = (PFNGLBUFFERSUBDATAPROC)load("glBufferSubData");
    glVERTEXATTRIBPOINTER = (PFNGLVERTEXATTRIBPOINTERPROC)load("glVertexAttribPointer");
    glENABLEVERTEXATTRIBARRAY = (PFNGLENABLEVERTEXATTRIBARRAYPROC)load("glEnableVertexAttribArray");
    glCREATESHADER = (PFNGLCREATESHADERPROC)load("glCreateShader");
    glSHADERSOURCE = (PFNGLSHADERSOURCEPROC)load("glShaderSource");
    glCOMPILESHADER = (PFNGLCOMPILESHADERPROC)load("glCompileShader");
    glGETSHADERIV = (PFNGLGETSHADERIVPROC)load("glGetShaderiv");
    glGETSHADERINFOLOG = (PFNGLGETSHADERINFOLOGPROC)load("glGetShaderInfoLog");
    glCREATEPROGRAM = (PFNGLCREATEPROGRAMPROC)load("glCreateProgram");
    glATTACHSHADER = (PFNGLATTACHSHADERPROC)load("glAttachShader");
    glLINKPROGRAM = (PFNGLLINKPROGRAMPROC)load("glLinkProgram");
    glGETPROGRAMIV = (PFNGLGETPROGRAMIVPROC)load("glGetProgramiv");
    glGETPROGRAMINFOLOG = (PFNGLGETPROGRAMINFOLOGPROC)load("glGetProgramInfoLog");
    glUSEPROGRAM = (PFNGLUSEPROGRAMPROC)load("glUseProgram");
    glGENFRAMEBUFFERS = (PFNGLGENFRAMEBUFFERSPROC)load("glGenFramebuffers");
    glBINDFRAMEBUFFER = (PFNGLBINDFRAMEBUFFERPROC)load("glBindFramebuffer");
    glFRAMEBUFFERTEXTURE2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC)load("glFramebufferTexture2D");
    glCHECKFRAMEBUFFERSTATUS = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)load("glCheckFramebufferStatus");
    glBLITFRAMEBUFFER = (PFNGLBLITFRAMEBUFFERPROC)load("glBlitFramebuffer");
    glGETUNIFORMLOCATION = (PFNGLGETUNIFORMLOCATIONPROC)load("glGetUniformLocation");
    glUNIFORM1F = (PFNGLUNIFORM1FPROC)load("glUniform1f");
    glUNIFORM1I = (PFNGLUNIFORM1IPROC)load("glUniform1i");
    glUNIFORM2F = (PFNGLUNIFORM2FPROC)load("glUniform2f");
    glUNIFORM3F = (PFNGLUNIFORM3FPROC)load("glUniform3f");
    glUNIFORM4F = (PFNGLUNIFORM4FPROC)load("glUniform4f");
    glUNIFORMMATRIX4FV = (PFNGLUNIFORMMATRIX4FVPROC)load("glUniformMatrix4fv");
    glDELETEPROGRAM = (PFNGLDELETEPROGRAMPROC)load("glDeleteProgram");
    glMAPBUFFER = (PFNGLMAPBUFFERPROC)load("glMapBuffer");
    glUNMAPBUFFER = (PFNGLUNMAPBUFFERPROC)load("glUnmapBuffer");
    glDELETEVERTEXARRAYS = (PFNGLDELETEVERTEXARRAYSPROC)load("glDeleteVertexArrays");
    glDELETEBUFFERS = (PFNGLDELETEBUFFERSPROC)load("glDeleteBuffers");
    glACTIVETEXTURE = (PFNGLACTIVETEXTUREPROC)load("glActiveTexture");
}
